= Restore

== Name
gdvc-restore - Getting the Gdvc marker and restoring from it

== Synopsis
gdvc restore [-s | --set] [--gmd] [-c | --clean]

== Description
Getting the level's special identifying Gdvc marker set with the init subcommand or changing it for restoration.

== Options
`-s` ::
`--set` ::

	Sets a marker for the level.

`--gmd` ::

	Restoring the marker using a gmd file.

`-c` ::
`--clean` ::

	Output the current marker without extra details.

== Why Is 0 An Invalid Value
The program uses the __kA26__ key in the level's metadata, it is present by default in every created level and always equals 0, so Gdvc considers that if __kA26__ is not 0, it is a Gdvc marker, and if it equals 0, the level is not initialized.

== Fun Fact
The Gdvc marker is just a timestamp recorded when the level was initialized, for a possible larger time range negative values are used (so the marker can store a value up to the year 2106 instead of 2038), but because of this when the timestamp equals the offset, the marker value will be 0, meaning the program will think the level is not initialized, this will happen on Jan 19 2038 03:14:08 for exactly one second.
